### ISSUE TITLE
Artist page blank for Beth Kille & Eric Kjelland

### ISSUE THREAD

**Issue by lahollen** [therabble/yahara#139]
The artist page is blank for recently added artist Beth Kille & Eric Kjelland. Album is North Star Sessions. 

http://www.yaharamusic.org/artist/beth-kille-erik-kjelland

Here is the info Guy sent to Matt:

Bio:
North Star Sessions is a collection of 7 original and one traditional winter/holiday/Christmas-themed songs penned and performed by Erik Kjelland (The Mascot Theory) and Beth Kille. Hailing from Madison, Wisconsin, Kjelland and Kille are no strangers to the joy, beauty and the perils of winter and holiday season.

As the co-founders of Flannel Fest (www.flannelfest.com), they are ardent supporters of the Americana music scene who began co-writing in the fall of 2013. Song themes include; struggling through the winter weather to return to a paramour after time on the road (North Star), trying to survive the dredge of the long, cold season by leaning on true love (Winter's Long Shadow), and making New Year's resolution to start living life to the fullest (December 31st). Kille and Kjelland harmonize throughout the album, blending their signature voices, in a style reminiscent of The Civll Wars or eastmountainsouth.

Links:
http://www.bethkille.com/
https://www.reverbnation.com/erikkjelland

![kille240678852_7750528943739650493_o](https://cloud.githubusercontent.com/assets/13225403/10769690/50fca6de-7cb5-11e5-9785-41a184b777ad.jpg)

**Comment by lahollen** [comment]
@mbrakken if this isn't the right repo please move

**Comment by mbrakken** [comment]
Ok. It's not working because there's no youtube url, and the current design assumes there always will be one.

I'll change that assumption.

**Comment by lahollen** [comment]
@mbrakken can you give me an update on this? Thanks!

**Comment by mbrakken** [comment]
Sorry, I haven't touched this at all. I need to figure out where everything
for YML lives (server, etc). Presumably the easiest thing at the moment is
for someone to add in some kind of youtube url.

**Comment by mbrakken** [comment]
Actually, I just looked again and I apparently gave myself access to YML's
server. I'll try to get this out today.

**Comment by lahollen** [comment]
@mbrakken - update? We're meeting with MPL folks Thursday and Guy will probably ask about the fix.

**Comment by kellyhiser** [comment]
Issue moved to [therabble/yahara-crosswalk #6](https://github.com/therabble/yahara-crosswalk/issues/6) via [**ZenHub**](https://www.zenhub.com/)
